export const firebase = {
    FIREBASE_UPDATE_REQUESTED: 'FIREBASE_UPDATE_REQUESTED',
    FIREBASE_UPDATE_FULFILLED: 'FIREBASE_UPDATE_FULFILLED',
    FIREBASE_UPDATE_REJECTED: 'FIREBASE_UPDATE_REJECTED',
};

export const metaTypes = {
  userContacts: 'userContacts',
};

export const eventTypes = {
    CHILD_ADDED: "CHILD_ADDED",
    CHILD_REMOVED: "CHILD_REMOVED",
    CHILD_CHANGED: "CHILD_CHANGED",
};